version: '3.9'
services:
  web:
    build: .
    ports:
      - '5000:5000'
  redis:
    image: 'redis:alpine'
  ubuntu-upstart:
    image: ubuntu-upstart
  solr:
    image: solr
    ports:
      - '8983'
